# ==========================================
# DEVELOPMENT PROFILE CONFIGURATIONS
# ==========================================

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
