
services:
  db:
    image: mysql:8.0
    container_name: employee-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pandi@1204
      MYSQL_DATABASE: employee_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./employee
      dockerfile: Dockerfile
    container_name: employee-backend
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/employee_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pandi@1204
      - SERVER_PORT=8080
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: employee-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
